image: reg.hawes.xyz/front-dl:latest

services:
- reg.hawes.xyz/mongodb:4.2.3

variables:
  C: 'curl -fsSL -w "\n" http://localhost:3000'

stages:
- build
- test
- push

cache:
  paths:
  - node_modules/

npm:
  stage: build
  script:
  - npm install
  - npm run bundle-prod
  artifacts:
    expire_in: 1 day
    paths:
    - node_modules/
    - bin/

api:
  stage: test
  script:
  - node app.js &
  - sleep 3
  - $C/api/settings
  - $C/api/version/ydl
  - $C/api/version/ffmpeg
  - $C/api/version/atomicparsley
  - $C/api/browse?path=

GitLab:
  stage: push
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/front-dl.dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --destination $CI_REGISTRY_IMAGE:latest
  only:
  - master

DockerHub:
  stage: push
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
  - echo "{\"auths\":{\"$DOCKERHUB_REGISTRY\":{\"username\":\"$DOCKERHUB_USER\",\"password\":\"$DOCKERHUB_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/front-dl.dockerfile --destination $DOCKERHUB_IMAGE:$CI_COMMIT_SHORT_SHA --destination $DOCKERHUB_IMAGE:latest
  only:
  - master