image: reg.hawes.xyz/front-dl:latest

services:
- reg.hawes.xyz/mongodb:4.2.3

variables:
  C: 'curl -fsSL http://localhost:3000'

stages:
- build
- test

cache:
  paths:
  - node_modules/

npm:
  stage: build
  script:
  - npm install
  - npm run bundle-prod
  artifacts:
    expire_in: 1 day
    paths:
    - node_modules/
    - bin/

api:
  stage: test
  script:
  - node app.js
  - sleep 3
  - $C/api/settings
  - $C/api/version/ydl
  - $C/api/version/ffmpeg
  - $C/api/version/atomicparsley
  - $C/api/browse?path=