version: '3.2'

services:
  nodejs:
    build:
      context: ./
      dockerfile: front-dl.dockerfile
    volumes:
      - type: bind
        source: /mnt/cephfs/media
        target: /mnt/ydl
    ports:
      - '3001:3000'
  mongodb:
    build:
      context: ./
      dockerfile: mongodb.dockerfile
    volumes:
      - type: bind
        source: /mnt/cephfs/db/front-dl
        target: /data/db
    network_mode: service:nodejs # Join nodejs' network namespace to connect db using localhost.