version: '3.2'

services:
  nodejs:
    build:
      context: ./
      dockerfile: front-dl-dev.dockerfile
    environment:
      DB_URL: mongodb://mongodb/front-dl
      # MODE: directory
      # FORMAT: audio
      # UID: 1234
      # GID: 4321
      # CHMOD: 777
      # EMBED_THUMBNAIL: 'false'
      # WRITE_THUMBNAIL: 'false'
    volumes:
      - type: bind
        source: ./
        target: /node
      - type: volume
        source: nodejs
        target: /media
      - type: volume
        source: cookies
        target: /etc/youtube-dl
    ports:
      - '3001:3000'
      - '9229:9229'
  mongodb:
    image: mongo:4.2.3
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
    ports:
      - '3002:27017'

volumes:
  nodejs:
  cookies:
  mongodb: