version: '3.2'

services:
  nodejs:
    build:
      context: ./
      dockerfile: front-dl.dockerfile
    environment:
      DB_URL: mongodb://mongodb/front-dl
    volumes:
      - type: volume
        source: nodejs
        target: /mnt/ydl
    ports:
      - '3001:3000'
  mongodb:
    build:
      context: ./
      dockerfile: mongodb.dockerfile
    volumes:
      - type: volume
        source: mongodb
        target: /data/db

volumes:
  nodejs:
  mongodb: