version: '3.2'

services:
  node.js:
    build:
      context: ./
      dockerfile: youtube-dl.dockerfile
    restart: unless-stopped
    volumes:
      - type: bind
        source: /mnt/cephfs/media
        target: /mnt/ydl
    ports:
      - '3001:3000'